config/routes.rb
Rails.application.routes.draw do
  get 'scrapes/index'
  get 'scrapes/edit'
  get 'scrapes/show'
  get 'scrapes/update'
  get 'scrapes/delete'
  resources :scrapes
  mount Resque::Server, at: "/jobs"

  # Web
  get "/webber", to: "application#index"


  # Api
  get "/scrape", to: "api/scrape#get"
end

app/models/container.rb
class Container
  include Mongoid::Document
  include Mongoid::Timestamps

  field :path, type: String
  field :elements, type: Array

  belongs_to :scrape
end

app/models/image.rb
class Image
  include Mongoid::Document
  include Mongoid::Timestamps

  field :url, type: String
  field :filetype, type: String
  embeds_one :size
  belongs_to :scrape
end

app/models/link.rb
class Link
  include Mongoid::Document
  include Mongoid::Timestamps

  field :url, type: String
  field :external, type: Boolean
  field :occurrences, type: Integer

  belongs_to :scrape
end

app/models/scrape.rb
class Scrape
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :url, type: String
  field :site_name, type: String
  has_many :images
  has_many :links
  has_many :containers
end

app/models/size.rb
class Size
  include Mongoid::Document

  field :amount, type: Integer
  field :measurement, type: String
  embedded_in :image
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API
  end
end

app/controllers/api/scrape_controller.rb
module Api
  class ScrapeController < ApplicationController
    def get
      # @todo: Actually do this in the background
      scrape = WebScrapeJob.perform_now(url: site_url_param)

      # @todo: Provide up-to-date execution status
      render json: scrape, include: [:links, :images, :containers]
    end

    private

    def site_url_param
      params[:url]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Service::Concerns::Fetchable
  include Service::Concerns::Parsable

  attr_reader :markup
  helper_method :markup

  def index
    fetch
  end

private

  def url_param
    params.require(:url)
  end

  def fetch
    document = (fetchable >> parsable).call(url_param)

    @markup ||= document.css(:head).inner_html + document.css(:body).inner_html
  end
end

app/controllers/scrapes_controller.rb
class ScrapesController < ApplicationController
  def index
  end

  def edit
  end

  def show
  end

  def update
  end

  def delete
  end
end

app/views/application/index.html.erb
<div class="Webber">
  <div class="WebScrape"></div>
  <%= render WebviewComponent.new(markup: markup) %>
</div>

app/views/layouts/application.html.erb
<html>
    <head></head>
    <body>
        <%= yield %>
    </body>
</html>

app/views/scrapes/_form.html.erb
<%= form_with(model: scrape, local: true) do |form| %>
  <% if scrape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scrape.errors.count, "error") %> prohibited this scrape from being saved:</h2>

      <ul>
        <% scrape.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :site_name %>
    <%= form.text_field :site_name %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_field :images %>
  </div>

  <div class="field">
    <%= form.label :links %>
    <%= form.text_field :links %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scrapes/delete.html.erb
<h1>Scrapes#delete</h1>
<p>Find me in app/views/scrapes/delete.html.erb</p>

app/views/scrapes/edit.html.erb
<h1>Editing Scrape</h1>

<%= render 'form', scrape: @scrape %>

<%= link_to 'Show', @scrape %> |
<%= link_to 'Back', scrapes_path %>

app/views/scrapes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scrapes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Site name</th>
      <th>Images</th>
      <th>Links</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scrapes.each do |scrape| %>
      <tr>
        <td><%= scrape.name %></td>
        <td><%= scrape.url %></td>
        <td><%= scrape.site_name %></td>
        <td><%= scrape.images %></td>
        <td><%= scrape.links %></td>
        <td><%= link_to 'Show', scrape %></td>
        <td><%= link_to 'Edit', edit_scrape_path(scrape) %></td>
        <td><%= link_to 'Destroy', scrape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scrape', new_scrape_path %>

app/views/scrapes/new.html.erb
<h1>New Scrape</h1>

<%= render 'form', scrape: @scrape %>

<%= link_to 'Back', scrapes_path %>

app/views/scrapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scrape.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @scrape.url %>
</p>

<p>
  <strong>Site name:</strong>
  <%= @scrape.site_name %>
</p>

<p>
  <strong>Images:</strong>
  <%= @scrape.images %>
</p>

<p>
  <strong>Links:</strong>
  <%= @scrape.links %>
</p>

<%= link_to 'Edit', edit_scrape_path(@scrape) %> |
<%= link_to 'Back', scrapes_path %>

app/views/scrapes/update.html.erb
<h1>Scrapes#update</h1>
<p>Find me in app/views/scrapes/update.html.erb</p>